FPS = 60
IMAGES_SIDE_SIZE = 112
COLS = 7
ROWS = 6
COLUMN_CHOOSING_MARGIN_TOP = 50
BOARD_MARGIN_TOP = IMAGES_SIDE_SIZE + COLUMN_CHOOSING_MARGIN_TOP
WINDOW_SIZE = (IMAGES_SIDE_SIZE * COLS, (IMAGES_SIDE_SIZE * ROWS) + BOARD_MARGIN_TOP)
SOUNDS_VOLUME = 0.5
COLORS = {
    'black': (0, 0, 0),
    'white': (255, 255, 255)
}
